= JSONテキストをpretty printしたい --- Gsonを使って

== 解決したい問題

Java8でプログラムを自作していた。
自作のJavaクラスにtoString()メソッドを実装しようとした。
どういう形式のテキストを出力 するのがいいかと考えて、JSONテキストを出力することにした。
たとえば自作のJavaクラスがこんなテキストを出力するとしよう。

[source]
----
{ "key": "profile", "value": "DevEnv_1.2.3-beta", "ignoredByKey": true, "identifiedByValue": true, "semanticVersion": "1.2.3-beta"}
----

正しい形式のJSONになっている。しかし見づらい。このテキストをコンソールに表示しても役に立たない。
適切な改行と字下げを付け加えたい。
任意のJSONテキストを入力として、適切な改行と字下げを加えたJSONテキストに変換する、というメソッドを作りたい。
たとえば上記の横長なJSONテキストを下記のような形式に直したい。

[source]
----
{
  "key": "profile",
  "value": "DevEnv_1.2.3-beta",
  "ignoredByKey": true,
  "identifiedByValue": true,
  "semanticVersion": "1.2.3-beta"
}
----

こういうテキスト変換をしてくれるヘルパを実装できればいいな。

"Java Json pretty print"とキーワードを指定してネットを検索した。
神々がおっしゃるには、JavaでJSONを操作するコードを書くならば

https://github.com/google/gson[Gson]

を使えという。ふむふむ。 見つかった記事を
https://www.baeldung.com/java-json[あれ]
https://qiita.com/u-chida/items/cbdd040e4199a10936dc[これ])
読んだ。わたしは困った。
それらネット記事はJavaオブジェクトとJSONテキストとを双方向に変換するあれこれややこしい話をしていた。
JavaオブジェクトをserializeしてJSONテキストにする。そのJSONテキストを入力として
Javaオブジェクトを復元する。ご苦労さまと思った。しかし僕はそんなことをしたいわけではない。
僕がしたいのはもっと低級なことだ。
JSON形式のStringを別のJSON形式のStringに変換したい、改行とインデントを加えたい、
それだけ。これを端的に例示してくれる記事がみつからなかった。

== 解決方法

困ったことに気づいてから、はや幾年。某日、ふと思いついた。たしかにGsonで解決できた。
たかだか数行のヘルパメソッドで。

== 説明

=== 入力データ

==== object.json

[source]
----
include::src/test/fixture/object.json[]
----

==== array.json

[source]
----
include::src/test/fixture/array.json[]
----

=== pretty printするヘルパクラス

[source,java]
----
include::src/main/java/my/JsonUtil.java[]
----

=== テスト

[source,java]
----
include::src/test/java/my/JsonUtilTest.java[]
----

=== テストを実行すると

[source]
----
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
---- array ----
[ "We are the champions, my friends", "Are we'll keep on fighting 'til the end.", "We are the champions.", "We are the champions.", "No time for losers", "'Cause we are the champions of the world."]
[
  "We are the champions, my friends",
  "Are we\u0027ll keep on fighting \u0027til the end.",
  "We are the champions.",
  "We are the champions.",
  "No time for losers",
  "\u0027Cause we are the champions of the world."
]
---- object ----
{ "key": "profile", "value": "DevEnv_1.2.3-beta", "ignoredByKey": true, "identifiedByValue": true, "semanticVersion": "1.2.3-beta"}
{
  "key": "profile",
  "value": "DevEnv_1.2.3-beta",
  "ignoredByKey": true,
  "identifiedByValue": true,
  "semanticVersion": "1.2.3-beta"
}
BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
10:21:10: Task execution finished ':test --tests "my.JsonUtilTest"'.
----

できた。




